"""add document metadata fields

Revision ID: f175c8590fc6
Revises: 2501602fc5ee
Create Date: 2026-06-05 16:00:15.964690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f175c8590fc6'
down_revision: Union[str, Sequence[str], None] = '2501602fc5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
